---
# Create the user to manage db
- name: Create postgres user
  become: yes
  become_user: postgres
  vars:
    ansible_ssh_pipelining: true
  postgresql_user:
    name: postgres
    password: secret
    encrypted: true
    role_attr_flags: CREATEDB
